devices: 
    # (mongo objectid) device subscription_id
  - subscription_id: <SUBSCRIPTION_ID>

    # (mongo objectid) device id 
    device_id: <DEVICE_ID>

    # (optional) name
    device_name: "dev1"

    # device value to seed
    value_name: "p"

    # Random bounds
    min: 0.0

    # Random bounds
    max: 2.0

    # "Add" :whether the to be added to the previous value | "Random": randomly generated values
    value_create_option: "Random"

    # how many month the device has been sending data
    months: 12

    # interval in seconds between 2 device messages
    interval: 15
    


    # (mongo objectid) device subscription_id
  - subscription_id: <SUBSCRIPTION_ID>

    # (mongo objectid) device id 
    device_id: <DEVICE_ID>

    # (optional) name
    device_name: "dev2"

    # device value to seed
    value_name: "p"

    # "Add" :whether the to be added to the previous value | "Random": randomly generated values
    value_create_option: "Random"

    # Random bounds
    min: 0.0

    # Random bounds
    max: 2.0

    # how many month the device has been sending data
    months: 12

    # interval in seconds between 2 device messages
    interval: 15

