
devices: 
  - id: "62c86fc4f5f01b39caa4caf2"
    repeat: true
    topic: "device/notification"
    interval: 2 #seconds
    values:
      - name: "s"
        value: 1
      - name: "u1"
        min: 0
        max: 250
      - name: "u2"
        min: 0
        max: 250
      - name: "u3"
        min: 0
        max: 250
      - name: "i1"
        min: 0
        max: 20
      - name: "i2"
        min: 0
        max: 20
      - name: "i3"
        min: 0
        max: 20
      - name: "p"
        min: 0
        max: 120
      - name: "e"
        min: 0
        max: 69

  - id: "62c86fd3f5f01b39caa4cb02"
    repeat: true
    topic: "device/notification"
    interval: 5 #seconds
    values:
      - name: "s"
        value: 1
      - name: "u1"
        min: 0
        max: 250
      - name: "u2"
        min: 0
        max: 250
      - name: "u3"
        min: 0
        max: 250
      - name: "i1"
        min: 0
        max: 20
      - name: "i2"
        min: 0
        max: 20
      - name: "i3"
        min: 0
        max: 20
      - name: "p"
        min: 0
        max: 120
      - name: "e"
        min: 0
        max: 69

  - id: "62c86fd9f5f01b39caa4cb12"
    repeat: true
    topic: "device/notification"
    interval: 8 #seconds
    values:
      - name: "s"
        value: 1
      - name: "u1"
        min: 0
        max: 250
      - name: "u2"
        min: 0
        max: 250
      - name: "u3"
        min: 0
        max: 250
      - name: "i1"
        min: 0
        max: 20
      - name: "i2"
        min: 0
        max: 20
      - name: "i3"
        min: 0
        max: 20
      - name: "p"
        min: 0
        max: 120
      - name: "e"
        min: 0
        max: 69
