name: "Build & Push Container"
on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@main

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: ./Cargo.toml
        id: version_check_staging

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./cli
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/energy-monitor-cli:${{ steps.version_check_staging.outputs.releaseVersion }},${{ secrets.DOCKER_HUB_USERNAME }}/energy-monitor-cli:latest
